import { Product } from './store';

export const categories = [
  { id: 'newborns', icon: '👶', color: 'coral' },
  { id: 'clothing', icon: '👕', color: 'mint' },
  { id: 'toys', icon: '🧸', color: 'sunny' },
  { id: 'strollers', icon: '🚼', color: 'lavender' },
  { id: 'furniture', icon: '🛏️', color: 'sky' },
  { id: 'school', icon: '📚', color: 'coral' },
  { id: 'hygiene', icon: '🧴', color: 'mint' },
  { id: 'feeding', icon: '🍼', color: 'sunny' },
  { id: 'development', icon: '🎨', color: 'lavender' },
  { id: 'sale', icon: '🏷️', color: 'coral' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Конструктор развивающий "Весёлые кубики"',
    nameKz: 'Дамытушы конструктор "Көңілді текшелер"',
    price: 12500,
    oldPrice: 15000,
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop',
    category: 'toys',
    ageRange: '1-3',
    brand: 'KidPlay',
    rating: 4.8,
    reviewsCount: 124,
    inStock: true,
    isNew: true,
    isSale: true,
  },
  {
    id: '2',
    name: 'Коляска прогулочная "Comfort Plus"',
    nameKz: 'Серуендеуге арналған арба "Comfort Plus"',
    price: 89900,
    image: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=400&h=400&fit=crop',
    category: 'strollers',
    ageRange: '0-3',
    brand: 'BabyComfort',
    rating: 4.9,
    reviewsCount: 89,
    inStock: true,
    isNew: true,
  },
  {
    id: '3',
    name: 'Комплект одежды для новорождённого',
    nameKz: 'Жаңа туған нәрестеге арналған киім жиынтығы',
    price: 15900,
    oldPrice: 19900,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop',
    category: 'newborns',
    ageRange: '0-1',
    brand: 'TinyTots',
    rating: 4.7,
    reviewsCount: 256,
    inStock: true,
    isSale: true,
  },
  {
    id: '4',
    name: 'Детский столик со стульями',
    nameKz: 'Балаларға арналған үстел мен орындықтар',
    price: 34500,
    image: 'https://images.unsplash.com/photo-1566873535350-a3f5d4a804b7?w=400&h=400&fit=crop',
    category: 'furniture',
    ageRange: '2-7',
    brand: 'KidsHome',
    rating: 4.6,
    reviewsCount: 78,
    inStock: true,
  },
  {
    id: '5',
    name: 'Мягкая игрушка "Зайка" 40 см',
    nameKz: 'Жұмсақ ойыншық "Қоян" 40 см',
    price: 7900,
    oldPrice: 9500,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    category: 'toys',
    ageRange: '0+',
    brand: 'SoftFriends',
    rating: 4.9,
    reviewsCount: 312,
    inStock: true,
    isSale: true,
  },
  {
    id: '6',
    name: 'Набор для кормления BabyFeed',
    nameKz: 'Тамақтандыруға арналған жиынтық BabyFeed',
    price: 8900,
    image: 'https://images.unsplash.com/photo-1584839404042-8bc21d240e61?w=400&h=400&fit=crop',
    category: 'feeding',
    ageRange: '0-2',
    brand: 'BabyFeed',
    rating: 4.5,
    reviewsCount: 167,
    inStock: true,
    isNew: true,
  },
  {
    id: '7',
    name: 'Рюкзак школьный "Космос"',
    nameKz: 'Мектеп рюкзагы "Ғарыш"',
    price: 12900,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
    category: 'school',
    ageRange: '6-12',
    brand: 'SchoolStar',
    rating: 4.7,
    reviewsCount: 201,
    inStock: true,
  },
  {
    id: '8',
    name: 'Развивающий коврик с дугами',
    nameKz: 'Доғалары бар дамытушы кілем',
    price: 19900,
    oldPrice: 24900,
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop',
    category: 'development',
    ageRange: '0-1',
    brand: 'PlayLearn',
    rating: 4.8,
    reviewsCount: 145,
    inStock: true,
    isSale: true,
  },
  {
    id: '9',
    name: 'Детский шампунь без слёз 300 мл',
    nameKz: 'Жылатпайтын балалар шампуні 300 мл',
    price: 2900,
    image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400&h=400&fit=crop',
    category: 'hygiene',
    ageRange: '0+',
    brand: 'BabyCare',
    rating: 4.6,
    reviewsCount: 423,
    inStock: true,
  },
  {
    id: '10',
    name: 'Кроссовки детские "Sport Kids"',
    nameKz: 'Балалар кроссовкалары "Sport Kids"',
    price: 15900,
    oldPrice: 18900,
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop',
    category: 'clothing',
    ageRange: '3-10',
    brand: 'SportKids',
    rating: 4.7,
    reviewsCount: 189,
    inStock: true,
    isSale: true,
  },
  {
    id: '11',
    name: 'Автокресло 0-25 кг "SafeRide"',
    nameKz: 'Автокресло 0-25 кг "SafeRide"',
    price: 67900,
    image: 'https://images.unsplash.com/photo-1544776193-352d25ca82cd?w=400&h=400&fit=crop',
    category: 'strollers',
    ageRange: '0-5',
    brand: 'SafeRide',
    rating: 4.9,
    reviewsCount: 156,
    inStock: true,
  },
  {
    id: '12',
    name: 'Набор красок для творчества',
    nameKz: 'Шығармашылыққа арналған бояулар жиынтығы',
    price: 4500,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop',
    category: 'development',
    ageRange: '3+',
    brand: 'ArtKids',
    rating: 4.5,
    reviewsCount: 234,
    inStock: true,
    isNew: true,
  },
];
